mixed-port: 10808
allow-lan: true
bind-address: '*'
mode: rule
log-level: info

dns:
    enable: true
    ipv6: false
    default-nameserver: [180.184.1.1, 180.184.2.2]
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    use-hosts: true
    nameserver: ['https://doh.pub/dns-query', 'https://dns.alidns.com/dns-query']
    fallback: ['https://cloudflare-dns.com/dns-query', 'tls://8.8.4.4:853']
    fallback-filter: { geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32] }

proxies:
  # 如果使用网络订阅这里可以留空
  # VMess
  # 支持的加密方法:
  #  auto/aes-128-gcm/chacha20-poly1305/none
  # - name: "BGS1"
  #   type: vmess
  #   server: 168.138.40.132
  #   port: 51002
  #   uuid: f9934026-5f46-11ec-bf63-0242ac130002
  #   alterId: 0
  #   cipher: auto
  #   # udp: true
  #   tls: false
  #   # skip-cert-verify: true
  #   # servername: example.com # 优先于 wss 主机
  #   network: ws
  #   # ws-opts:
  #   #   path: /path
  #   #   headers:
  #   #     Host: v2ray.com
  #   #   max-early-data: 2048
  #   #   early-data-header-name: Sec-WebSocket-Protocol

  #- { name: GS01, type: vmess, server: 168.138.40.132, port: 51002, uuid: f9934026-5f46-11ec-bf63-0242ac130002, alterId: 0, cipher: auto, tls: false, network: ws }
  - {name: GS01, server: 162.159.192.213, port: 4500, type: wireguard, public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=, private-key: iOry7yqHa54QxOluEJ/zgu3IpXgjWhJTVQP75GdyDV8=, ip: 172.16.0.2, ipv6: 2606:4700:110:8ffa:4297:723a:d108:9f0a, dns: [1.1.1.1, 8.8.8.8], mtu: 1280, udp: true}

proxy-groups:
    - { name: GS, type: select, proxies: [ 上网专用, 游戏专用, 其它云, GS01 ] }
    - { name: 上网专用, type: select, use: [ GS小鸡 ], url: 'http://www.gstatic.com/generate_204', interval: 86400 }
    #- { name: 故障转移, type: fallback, use: [GS小鸡], url: 'http://www.gstatic.com/generate_204', interval: 7200 }
    - { name: 游戏专用, type: select, use: [ 游戏专用 ], url: 'http://www.gstatic.com/generate_204', interval: 86400 }
    - { name: 其它云, type: select, use: [ 其它云 ], url: 'http://www.gstatic.com/generate_204', interval: 86400 }

proxy-providers:
  GS小鸡:
    type: http
    #url: "https://v1.mk/pHhZYyn"     # 将机场的提供的clash订阅地址拷贝进来,如果没有clash订阅地址,请使用https://sub.v1.mk/进行地址转换
    url: 'https://mirror.ghproxy.com/https://raw.githubusercontent.com/mgit0001/test_clash/main/gs.yaml'
    path: "./gs.yaml"             # 将机场的clash配置下载后存放的位置
    interval: 86400                 # 每隔86400秒即每隔1天从url中指定的clash订阅地址更新
    health-check:                  # 节点健康检查类似ping测试
      enable: true
      interval: 3600                # 每隔3600秒测试一次延迟
      url: http://www.gstatic.com/generate_204

  游戏专用:
    type: http
    #url: "https://v1.mk/pHhZYyn"     # 将机场的提供的clash订阅地址拷贝进来,如果没有clash订阅地址,请使用https://sub.v1.mk/进行地址转换
    url: 'https://mirror.ghproxy.com/https://raw.githubusercontent.com/mgit0001/test_clash/main/gsgame.yaml'
    path: "./gsgame.yaml"             # 将机场的clash配置下载后存放的位置
    interval: 86400                 # 每隔86400秒即每隔1天从url中指定的clash订阅地址更新
    health-check:                  # 节点健康检查类似ping测试
      enable: true
      interval: 3600                # 每隔3600秒测试一次延迟
      url: http://www.gstatic.com/generate_204

  其它云:
    type: http
    #url: "https://v1.mk/pHhZYyn"     # 将机场的提供的clash订阅地址拷贝进来,如果没有clash订阅地址,请使用https://sub.v1.mk/进行地址转换
    url: 'https://mirror.ghproxy.com/https://raw.githubusercontent.com/mgit0001/test_clash/main/tgs.yaml'
    path: "./otherclouds.yaml"             # 将机场的clash配置下载后存放的位置
    interval: 86400                 # 每隔86400秒即每隔1天从url中指定的clash订阅地址更新
    health-check:                  # 节点健康检查类似ping测试
      enable: true
      interval: 3600                # 每隔3600秒测试一次延迟
      url: http://www.gstatic.com/generate_204

#===================== 配置规则 =====================#
# 配置联网规则
rule-providers:
  # 广告域名列表
  Reject:
    type: http
    behavior: domain
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt"
    path: ./ruleset/Reject.yaml
    interval: 86400
  
  # 代理域名列表
  Proxy:
    type: http
    behavior: domain
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt"
    path: ./ruleset/Proxy.yaml
    interval: 86400  
  
  Google:
    type: http
    behavior: classical
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Google.yaml"
    path: ./ruleset/Google.yaml
    interval: 86400

  YouTube:
    type: http
    behavior: classical
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/YouTube.yaml"
    path: ./ruleset/YouTube.yaml
    interval: 86400

  Netflix:
    type: http
    behavior: classical
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Netflix.yaml"
    path: ./ruleset/Netflix.yaml
    interval: 86400
  
  OneDrive:
    type: http
    behavior: classical
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/OneDrive.yaml"
    path: ./ruleset/OneDrive.yaml
    interval: 86400

  Bilibili:
   type: http
   behavior: classical
   url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Bilibili.yaml"
   path: ./ruleset/Bilibili.yaml
   interval: 86400  
  
  DisneyPlus:
    type: http
    behavior: classical
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/DisneyPlus.yaml"
    path: ./ruleset/DisneyPlus.yaml
    interval: 86400  

  HBO:
    type: http
    behavior: classical
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/HBO.yaml"
    path: ./ruleset/HBO.yaml
    interval: 86400  

  NetEaseMusic:
    type: http
    behavior: classical
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/NetEaseMusic.yaml"
    path: ./ruleset/NetEaseMusic.yaml
    interval: 86400    

  WeChat:
    type: http
    behavior: classical
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Wechat.yaml"
    path: ./ruleset/WeChat.yaml
    interval: 86400    
  
  SteamCN:
    type: http
    behavior: classical
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/SteamCN.yaml"
    path: ./ruleset/SteamCN.yaml
    interval: 86400  
  
  Steam:
    type: http
    behavior: classical
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Steam.yaml"
    path: ./ruleset/Steam.yaml
    interval: 86400  
    
  Xbox:
    type: http
    behavior: classical
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Xbox.yaml"
    path: ./ruleset/Xbox.yaml
    interval: 86400  

  Apple:
    type: http
    behavior: domain 
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt"
    path: ./ruleset/Apple.yaml
    interval: 86400  
  
  # iCloud 域名列表
  icloud:
    type: http
    behavior: domain
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  # 需要直连的常见软件列表
  applications:
    type: http
    behavior: classical
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400
  
  # 直连域名列表
  Direct:
    type: http
    behavior: domain
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt"
    path: ./ruleset/Direct.yaml
    interval: 86400
  
  # 私有网络专用域名列表
  Private:
    type: http
    behavior: domain
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt"
    path: ./ruleset/Private.yaml
    interval: 86400
  
  # GFWList 域名列表
  GFW:
    type: http
    behavior: domain
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt"
    path: ./ruleset/GFW.yaml
    interval: 86400
  
  GreatFire:
    type: http
    behavior: domain
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/greatfire.txt"
    path: ./ruleset/GreatFire.yaml
    interval: 86400
  
  #非中国大陆使用的顶级域名列表
  Tld-Not-CN: 
    type: http
    behavior: domain
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/tld-not-cn.txt"
    path: ./ruleset/Tld-Not-CN.yaml
    interval: 86400

  # Telegram 使用的 IP 地址列表
  TelegramCidr:
    type: http
    behavior: ipcidr
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/telegramcidr.txt"
    path: ./ruleset/TelegramCidr.yaml
    interval: 86400
  
  #中国大陆 IP 地址列表
  CnCidr:
    type: http
    behavior: ipcidr
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt"
    path: ./ruleset/CnCidr.yaml
    interval: 86400
  
  #局域网 IP 及保留 IP 地址列表
  LanCidr:
     type: http
     behavior: ipcidr
     url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt"
     path: ./ruleset/LanCidr.yaml
     interval: 86400
  

# 配置自定义规则
rules:
  # 直连规则
  - DOMAIN,clash.razord.top,DIRECT,no-resolve
  - DOMAIN,yacd.haishan.me,DIRECT,no-resolve

  # OneDrive规则
  - DOMAIN-SUFFIX,youngqfbr-my.sharepoint.com,GS,no-resolve
  - DOMAIN-KEYWORD,sharepoint.com,GS,no-resolve
  - DOMAIN-KEYWORD,onedrive,GS,no-resolve

  # GoogleDrive规则
  - DOMAIN-SUFFIX,googleapis.com,GS,no-resolve
  - IP-CIDR,172.217.160.106/32,GS,no-resolve
  - PROCESS-NAME,com.ss.android.ugc.trill,GS,no-resolve
  - DOMAIN-SUFFIX,byteoversea.com,GS,no-resolve
  - DOMAIN-SUFFIX,ibytedtos.com,GS,no-resolve
  - DOMAIN-SUFFIX,ipstatp.com,GS,no-resolve
  - DOMAIN-SUFFIX,muscdn.com,GS,no-resolve
  - DOMAIN-SUFFIX,musical.ly,GS,no-resolve
  - DOMAIN-SUFFIX,tiktok.com,GS,no-resolve
  - DOMAIN-SUFFIX,tiktokcdn.com,GS,no-resolve
  - DOMAIN-SUFFIX,tiktokv.com,GS,no-resolve
  - DOMAIN-KEYWORD,-tiktokcdn-com,GS,no-resolve
  - DOMAIN-KEYWORD,tophup.today,GS,no-resolve
  - DOMAIN-KEYWORD,cli.im,DIRECT,no-resolve
  
  # Open AI Rule
  - DOMAIN-SUFFIX,openai.com,GS,no-resolve
  - DOMAIN-SUFFIX,chat.openai.com,GS,no-resolve
  - DOMAIN-SUFFIX,challenges.cloudflare.com,GS,no-resolve
  - DOMAIN-SUFFIX,auth0.openai.com,GS,no-resolve
  - DOMAIN-SUFFIX,platform.openai.com,GS,no-resolve
  - DOMAIN-SUFFIX,ai.com,GS,no-resolve
  - DOMAIN-KEYWORD,bing.com,GS,no-resolve
  
  # Server rule
  - IP-CIDR,18.163.116.27/32,GS,no-resolve
  - IP-CIDR,143.42.76.210/32,GS,no-resolve
  - DOMAIN-KEYWORD,archer.now.cc,GS,no-resolve

  # ---------------自用配置-------------------------------
  - DOMAIN-SUFFIX,yunweipai.com,DIRECT
  - DOMAIN-SUFFIX,51yip.com,DIRECT
  - DOMAIN-SUFFIX,gshis.com,DIRECT
  - DOMAIN-SUFFIX,hualala.com,DIRECT
  - DOMAIN-SUFFIX,cheweiguanjia.com,DIRECT
  - DOMAIN-SUFFIX,vn.mk,DIRECT
  - DOMAIN-SUFFIX,goorm.io,DIRECT,no-resolve
  # -----------------------------------------------------

  # 规则集命中规则 
  - RULE-SET,Reject,REJECT,no-resolve
  - RULE-SET,Google,GS,no-resolve
  - RULE-SET,YouTube,GS,no-resolve
  - RULE-SET,Netflix,GS,no-resolve
  - RULE-SET,HBO,GS,no-resolve
  - RULE-SET,OneDrive,GS,no-resolve
  - RULE-SET,DisneyPlus,GS,no-resolve
  - RULE-SET,Apple,GS,no-resolve

  - RULE-SET,Steam,GS,no-resolve
  - RULE-SET,Xbox,GS,no-resolve
  - RULE-SET,Proxy,GS,no-resolve
  - RULE-SET,GFW,GS,no-resolve
  - RULE-SET,GreatFire,GS,no-resolve
  - RULE-SET,Tld-Not-CN,GS,no-resolve
  - RULE-SET,TelegramCidr,GS,no-resolve

  - RULE-SET,Bilibili,DIRECT,no-resolve
  - RULE-SET,icloud,DIRECT,no-resolve
  - RULE-SET,applications,DIRECT,no-resolve
  - RULE-SET,Direct,DIRECT,no-resolve
  - RULE-SET,Private,DIRECT,no-resolve
  - RULE-SET,WeChat,DIRECT,no-resolve
  - RULE-SET,SteamCN,DIRECT,no-resolve
  - RULE-SET,NetEaseMusic,DIRECT,no-resolve
  - RULE-SET,CnCidr,DIRECT,no-resolve
  - RULE-SET,LanCidr,DIRECT,no-resolve

  # 其它规则 
  - GEOIP,CN,DIRECT,no-resolve
  - MATCH,GS
  



